version: "3"

services:
  nginx:
    container_name: shop-nginx
    image: nginx:1.17
    volumes:
      - ./src:/var/www/shop
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
      - ./src/catalog/controller/extension/feed/sitemap.xml:/var/www/sitemap.xml
    ports:
      - 80:80
      - 443:443
    links:
      - php
    depends_on:
      - php
  
  certbot:
    container_name: shop-certbot
    image: certbot/certbot
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot

  php:
    container_name: shop-php
    image: php-shop
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./src:/var/www/shop
    ports:
      - 9000:9000
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: shop-mysql
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop
      - MYSQL_USER=shop
      - MYSQL_PASSWORD=shop
      - TZ=Etc/UTC
    restart: on-failure
