version: "3.7"

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./src:/var/www/shop
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - php

  php:
    container_name: php-shop
    image: php-shop
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./src:/var/www/shop
    ports:
      - 9999:9000
    links:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop
      - MYSQL_USER=shop
      - MYSQL_PASSWORD=shop
      - TZ=Etc/UTC
    restart: on-failure